# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='doginfo',
            name='DogPrice',
        ),
        migrations.AddField(
            model_name='doginfo',
            name='DogType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dog.DogType'),
            preserve_default=False,
        ),
    ]
