# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doginfo',
            name='Author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dog.UserProfile'),
            preserve_default=False,
        ),
    ]
