# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 06:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dog', '0005_auto_20160504_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doginfo',
            name='Author',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='dog.UserProfile'),
            preserve_default=False,
        ),
    ]
