# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0009_auto_20160504_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='doginfo',
            name='Create_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 5, 15, 9, 13, 45, 4000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doginfo',
            name='Update_date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 5, 15, 9, 13, 56, 333000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
